import { Router, type IRouter } from "express";
import healthRouter from "./health";
import mathRouter from "./math";
import historyRouter from "./history";
import aiRouter from "./ai";
import externalRouter from "./external";
import authRouter from "./auth";
import tokensRouter from "./tokens";
import storageRouter from "./storage";
import resourcesRouter from "./resources";
import novelsRouter from "./novels";
import quizRouter from "./quiz";
import ratingsRouter from "./ratings";
import adminRouter from "./admin";
import xpRouter from "./xp";
import errorsRouter from "./errors";
import activityRouter from "./activity";
import pdfsRouter from "./pdfs";
import billingRouter from "./billing";
import communityRouter from "./community";
import streakRouter from "./streak";
import guestRouter from "./guest";
import referralRouter from "./referral";
import supportRouter from "./support";
import documentsRouter from "./documents";

const router: IRouter = Router();


router.use(authRouter);
router.use(healthRouter);
router.use(mathRouter);
router.use(historyRouter);
router.use(aiRouter);
router.use(externalRouter);
router.use(tokensRouter);
router.use(storageRouter);
router.use(resourcesRouter);
router.use(documentsRouter);
router.use("/novels", novelsRouter);
router.use("/quiz", quizRouter);
router.use(ratingsRouter);
router.use(adminRouter);
router.use(xpRouter);
router.use(errorsRouter);
router.use(activityRouter);
router.use(pdfsRouter);
router.use(billingRouter);
router.use(communityRouter);
router.use(streakRouter);
router.use(guestRouter);
router.use(referralRouter);
router.use(supportRouter);

export default router;
