export const CALC_KEYS = [
  ["7", "8", "9", "÷", "("],
  ["4", "5", "6", "×", ")"],
  ["1", "2", "3", "-", "^"],
  ["0", ".", "π", "+", "√"],
  ["sin(", "cos(", "tan(", "log(", "⌫"],
  ["(", ")", "e", "!", "⌦"],
];

export interface CalcSection {
  label: string;
  color: string;
  bg: string;
  border: string;
  cols: number;
  keys: string[];
}

export const ADVANCED_SECTIONS: CalcSection[] = [
  {
    label: "Numbers & Operators",
    color: "text-slate-200", bg: "bg-slate-500/8", border: "border-slate-500/20",
    cols: 6,
    keys: ["7","8","9","÷","(",")", "4","5","6","×","^","=", "1","2","3","−",".","!", "0","+","x","y","n","%"],
  },
  {
    label: "Edit",
    color: "text-orange-300", bg: "bg-orange-500/8", border: "border-orange-500/20",
    cols: 2,
    keys: ["⌫","⌦"],
  },
  {
    label: "Variables",
    color: "text-violet-300", bg: "bg-violet-500/8", border: "border-violet-500/20",
    cols: 8,
    keys: ["x","y","z","a","b","n","k","m","t","r","θ","λ","α","β","γ","δ"],
  },
  {
    label: "Powers & Roots",
    color: "text-teal-300", bg: "bg-teal-500/8", border: "border-teal-500/20",
    cols: 6,
    keys: ["x²","x³","x⁻¹","x^n","^½","^⅓","√(","∛(","∜(","abs(","floor(","ceil("],
  },
  {
    label: "Trigonometry",
    color: "text-purple-300", bg: "bg-purple-500/8", border: "border-purple-500/20",
    cols: 6,
    keys: ["sin(","cos(","tan(","asin(","acos(","atan(","sinh(","cosh(","tanh(","cot(","sec(","csc("],
  },
  {
    label: "Logarithms & Exponentials",
    color: "text-blue-300", bg: "bg-blue-500/8", border: "border-blue-500/20",
    cols: 6,
    keys: ["log(","ln(","log2(","log10(","exp(","e^("],
  },
  {
    label: "Constants",
    color: "text-amber-300", bg: "bg-amber-500/8", border: "border-amber-500/20",
    cols: 8,
    keys: ["π","e","i","∞","φ","τ","ℏ","c"],
  },
  {
    label: "Greek Letters",
    color: "text-rose-300", bg: "bg-rose-500/8", border: "border-rose-500/20",
    cols: 8,
    keys: ["α","β","γ","δ","ε","ζ","η","θ","ι","κ","λ","μ","ν","ξ","ρ","σ","τ","υ","φ","χ","ψ","ω","Δ","Σ","Γ","Λ","Ω","∂"],
  },
  {
    label: "Calculus",
    color: "text-cyan-300", bg: "bg-cyan-500/8", border: "border-cyan-500/20",
    cols: 6,
    keys: ["∫(","d/dx ","lim(","∑(","∏(","∂/∂x "],
  },
  {
    label: "Symbols & Comparisons",
    color: "text-orange-300", bg: "bg-orange-500/8", border: "border-orange-500/20",
    cols: 8,
    keys: ["≤","≥","≠","≈","≡","<",">","=","{","}","[","]","|","‖","→","⇒"],
  },
];

export const KEY_MAP: Record<string, string> = {
  "÷": "/",
  "×": "*",
  "−": "-",
  "π": "pi",
  "√": "sqrt(",
  "√(": "sqrt(",
  "∛(": "cbrt(",
  "∜(": "nthRoot(",
  "e": "e",
  "!": "!",
  "x²": "^2",
  "x³": "^3",
  "x⁻¹": "^(-1)",
  "x^n": "^",
  "^½": "^(1/2)",
  "^⅓": "^(1/3)",
  "∞": "Infinity",
  "φ": "phi",
  "τ": "tau",
  "ℏ": "hbar",
  "c": "c",
  "α": "alpha",
  "β": "beta",
  "γ": "gamma",
  "δ": "delta",
  "ε": "epsilon",
  "ζ": "zeta",
  "η": "eta",
  "θ": "theta",
  "ι": "iota",
  "κ": "kappa",
  "λ": "lambda",
  "μ": "mu",
  "ν": "nu",
  "ξ": "xi",
  "ρ": "rho",
  "σ": "sigma",
  "υ": "upsilon",
  "χ": "chi",
  "ψ": "psi",
  "ω": "omega",
  "Δ": "Delta",
  "Σ": "Sigma",
  "Γ": "Gamma",
  "Λ": "Lambda",
  "Ω": "Omega",
  "∂": "d",
  "∫(": "integral(",
  "d/dx ": "d/dx ",
  "lim(": "lim(",
  "∑(": "sum(",
  "∏(": "product(",
  "∂/∂x ": "d/dx ",
  "≤": "<=",
  "≥": ">=",
  "≠": "!=",
  "≈": "~",
  "≡": "==",
  "→": "->",
  "⇒": "=>",
  "‖": "||",
  "abs(": "abs(",
  "floor(": "floor(",
  "ceil(": "ceil(",
  "asin(": "asin(",
  "acos(": "acos(",
  "atan(": "atan(",
  "sinh(": "sinh(",
  "cosh(": "cosh(",
  "tanh(": "tanh(",
  "cot(": "cot(",
  "sec(": "sec(",
  "csc(": "csc(",
  "log2(": "log(2,",
  "log10(": "log(10,",
  "exp(": "exp(",
  "e^(": "e^(",
};
